### ISSUE TITLE
Github Actions for CI

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/botok#63]
I've recently moved to using Github's integrated CI for all my projects. The experience is very good in comparison to the old way (e.g. Travis etc.). 

It's not enabled by default, but you can do it [here](https://github.com/features/actions/signup).

I could move the current CI to Github, as well as have a look if there are some obvious improvements we could make in the process.

**Comment by 10zinten** [comment]
I have successfully implemented it in openpecha-toolkit, the Test and Publishing to Pypi
https://github.com/OpenPecha/openpecha-toolkit/tree/master/.github/workflows

Test is run on every push and Pypi publish is done on very tag push.

**Comment by 10zinten** [comment]
resolved https://github.com/Esukhia/botok/commit/87bb60a7b98ac89aaf9c2020d552ed2192ac4a17
