### ISSUE TITLE
Missing lemma for numbers

### ISSUE THREAD

**Issue by 10zinten** [Esukhia/botok#65]
Here is output after the tokenization with latest botok.

![lemma_01](https://user-images.githubusercontent.com/16164304/67835265-87076200-fb0f-11e9-8ea3-11d30fb2af05.png)
![lemma_02](https://user-images.githubusercontent.com/16164304/67835271-8a025280-fb0f-11e9-99ce-e92afc301acd.png)
![lemma_03](https://user-images.githubusercontent.com/16164304/67835276-8bcc1600-fb0f-11e9-98e3-4c4e84c12eb9.png)
![lemma_05](https://user-images.githubusercontent.com/16164304/67835280-8e2e7000-fb0f-11e9-8337-8f83195dda03.png)

**Comment by drupchen** [comment]
Ok. I see. The merging matcher that put the པ་ in the number's token emptied the lemma. I'll have a look at it. Envoyé depuis mon téléphone Huawei-------- Message original --------Objet : [Esukhia/botok] Missing lemma for numbers (#65)De : Tenzin À : Esukhia/botok Cc : Subscribed Here is output after the tokenization with latest botok.

**Comment by drupchen** [comment]
fixed in https://github.com/Esukhia/botok/commit/d146284c6f015c29d56c4661cce5da3330aba84f

**Comment by drupchen** [comment]
bugfix is now in release 0.6.13
In the future, when you miss a lemma, you can simply use `Token.text_cleaned` instead.
